[package]
name = "mu_leet_code"
version = "0.1.0"
authors = ["Murphy.W.Zhu <Murphy.W.Zhu@aliyun.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
